root = "."
tmp_dir = "tmp"

[build]
	cmd = "go build -o ./tmp/main ./cmd/web/main.go"
	bin = "./tmp/main"
	include_ext = ["go", "html", "css"]
	exclude_dir = ["tmp","bin"]
	delay = 1000

[log]
	time = true

[misc]
	clean_on_exit = true
