root = "."
tmp_dir = "tmp/build"

[build]
    cmd = "go build -o ./tmp/build/main ./cmd/web/main.go"
    entrypoint = ["./tmp/build/main"]
    bin = "./tmp/build/main"
    
    include_ext = ["go", "tpl", "tmpl", "html", "sql"]
    exclude_dir = ["assets", "tmp", "vendor", "bin"]
    delay = 1000
    log_level = "debug"

[log]
	time = true

[misc]
	clean_on_exit = true
